development:
  adapter: async
#  adapter: redis
#  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.env.production? ? ENV.fetch("REDIS_URL") : ENV["REDIS_URL"] %>
  channel_prefix: touhyosan_production
